version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: retro-mike-xmr-node_web_1
      APP_PORT: 8080
  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - node
  node:
    image: theretromike/nodes:monero
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.monero:/root/.bitmonero
    ports:
      - 9009:9009    # RPC
      - 7009:7009    # ZMQ
      - 18080:18080    # P2P
    entrypoint: "monerod --non-interactive --out-peers 32 --p2p-bind-ip=0.0.0.0 --p2p-bind-port=18080 --rpc-bind-ip=127.0.0.1 --rpc-bind-port=9009 --prune-blockchain --zmq-pub=tcp://127.0.0.1:7009"
