version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: retro-mike-miningcore-webui_web_1
      APP_PORT: 8081
  web:
    image: theretromike/miningcorewebui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - server
    environment:
      - POOL_NAME="Self-Hosted Mining Pool"
      - STRATUM_HOST="192.168.1.100"
      - API_BASE_URL="http://192.168.1.100:4000/api"
