version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: retro-mike-miningcore-webui_web_1
      APP_PORT: 8080
  web:
    image: theretromike/miningcorewebui
#    ports:
#      - 5002:8080
    restart: on-failure
    environment:
      - POOL_NAME=Self-Hosted Mining Pool
      - STRATUM_HOST=$HOSTNAME
      - API_BASE_URL=http://umbrel:4000/api
