version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: retro-mike-ppc-node_web_1
      APP_PORT: 8080
  web:
    image: amir20/dozzle:v8.12.8@sha256:8ff3115c9c9dd7576839df6f2575de345ca7cafa398cf2496f1f19c31d862ac1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - node
  node:
    image: theretromike/nodes:peercoin
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.peercoin:/root/.peercoin
    ports:
      - 9012:9012    # RPC
      - 7012:7012    # ZMQ
      - 9901:9901    # P2P
    entrypoint: "peercoind -printtoconsole -server -wallet=default -zmqpubhashblock=tcp://0.0.0.0:7012 -rpcbind=0.0.0.0 -rpcport=9012 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
