version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: retro-mike-postgres_web_1
      APP_PORT: 80

  web:
    image: dpage/pgadmin4:latest
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PGADMIN_DEFAULT_EMAIL: umbrel@umbrel.com
      PGADMIN_DEFAULT_PASSWORD: umbrel
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin

  db:
    image: postgres:16
    restart: on-failure
    stop_grace_period: 1m
    environment:
      POSTGRES_DB: umbrel
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - ${APP_DATA_DIR}/pgadmin:/var/lib/pgadmin
      - ${APP_DATA_DIR}/pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - 5432:5432
